format_version: 9
pipelines:
  test_application:
    group: sample
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 2
    environment_variables:
    materials:
      upstream:
        pipeline: build_and_publish_image_php
        stage: build_and_publish_image_php
        name: upstream
    stages:
    - test_app_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          test_app_image:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                artifact_id: app-web-php
                pipeline: build_and_publish_image_php
                stage: build_and_publish_image_php
                job: build_image_php
                artifact_origin: external
                run_if: passed
            - exec:
                arguments:
                - -c
                - kubectl get namespaces
                command: /bin/bash
                run_if: passed
